name: Build sketch
on: [push, pull_request]
jobs:
  build:
    name: Build sketch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout ESPAsyncWebServer library
        uses: actions/checkout@v2
        with:
          repository: me-no-dev/ESPAsyncWebServer
          ref: master
          path: CustomESPAsyncWebServer # must contain string "Custom"

      - name: Checkout AsyncElegantOTA library
        uses: actions/checkout@v2
        with:
          repository: ayushsharma82/AsyncElegantOTA
          ref: master
          path: CustomAsyncElegantOTA

      - name: Checkout AsyncTCP library
        uses: actions/checkout@v2
        with:
          repository: me-no-dev/AsyncTCP
          ref: master
          path: CustomAsyncTCP

      - name: "Compile sketch"
        uses: ArminJo/arduino-test-compile@v3
        with:
          sketch-names: "solvinden.ino"
          arduino-board-fqbn: "esp32:esp32:esp32:PSRAM=disabled,PartitionScheme=default,CPUFreq=240,FlashMode=qio,FlashFreq=80,FlashSize=4M,UploadSpeed=115200,LoopCore=1,EventsCore=1,DebugLevel=none"
          platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          required-libraries: HomeSpan
